#print(input('Digite seu nome: '))
nome = input('Qual seu nome? ')
idade = int(input('Qual sua idade? '))
altura = float(input('Digite a sua altura: '))
print('Olá {}, sua idade é {} e sua altura é {:.2f}m.'.format(nome, idade, altura))
